nats:
  host: "nats://localhost"
  port: 4222
  request_channel: "prediction_request_channel"
  response_channel: "prediction_response_channel"

api:
  host: "http://localhost"
  port: 8000
  prediction: "/predict"
